import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import {
  Input,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  Image,
  Stack,
  Text,
  Button,
  ButtonGroup,
  Box,
  Tabs, 
  TabList,
  TabPanels, 
  Tab, 
  TabPanel,
  Select,
} from "@chakra-ui/react"

export default function Home() {
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>Fin Postulacion</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/utfsm.ico" />
            </Head>

        <main className={styles.main}>

        <Box bg='#319795' w='100%' p={2} color='white'>
          <Stack spacing={4} direction='row' align='center'>
            <Button colorScheme="#319795" size="md" onClick={() => router.push("http://localhost:3000")}>Inicio</Button>
            <Button colorScheme="#319795" size="md" onClick={() => router.push("login")}>Iniciar sesión</Button>
          </Stack>
        </Box>
        
        <Image src='/utfsmlogo.png' alt='UTFSM' />
        
        <Image src='/portada.jpeg' alt='UTFSM' />

        <Box bg='white' w='100%' p={4} color='white'/>

        <Box bg="#319795" w="100%" p={4} color="white">

        <Text fontSize="2xl">La postulación ha sido ingresada con éxito.</Text>

        <Stack direction="row" spacing={4} align="center">
            <Button colorScheme="blue" size="md" onClick={() => router.push("http://localhost:3000")}>Volver a la página principal</Button>
        </Stack>
        
        </Box>
      </main>
    </div>
    )
}    
