import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box,Button, ButtonGroup, Input, Text, Stack} from "@chakra-ui/react"
import { useRouter } from 'next/router'
import { Image } from '@chakra-ui/react'

export default function Home() {
    const router = useRouter()
    return (
      <div className={styles.container}>
        <Head>
          <title>Recuperar Contraseña</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/utfsm.ico" />
        </Head>

        <main className={styles.main}>

        <Box bg='#319795' w='100%' p={2} color='white'>
          <Stack spacing={4} direction='row' align='center'>
            <Button colorScheme="#319795" size="md" onClick={() => router.push("postulacion")}>Inicio</Button>
            <Button colorScheme="#319795" size="md" onClick={() => router.push("postulacion")}>Iniciar sesión</Button>
          </Stack>
        </Box>
        
        <Image src='/utfsmlogo.png' alt='UTFSM' />
        
        <Image src='/portada.jpeg' alt='UTFSM' />

        <Text fontSize='4xl'>Campus y Sedes</Text>
  
        <Stack spacing={4} direction='row' align='center'>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Campus Casa Central Valparaíso</Text>
          <Image src='/utfsmfront.jpg' alt='UTFSM-CC' />
        </Box>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Campus San Joaquín</Text>
          <Image src='/sanjoaquin.jpg' alt='UTFSM' />
        </Box>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Campus Vitacura</Text>
          <Image src='/vitacura.jpg' alt='UTFSM' />
        </Box>
        </Stack>
        <Stack spacing={4} direction='row' align='center'>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Sede Viña del Mar</Text>
          <Image src='/sedeviña.jpg' alt='UTFSM' />
        </Box>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Sede Concepción</Text>
          <Image src='/concepcion.jpg' alt='UTFSM' />
        </Box>
        <Box boxSize='sm'>
          <Text fontSize='2xl' align='center'>Campus Guayaquil</Text>
          <Image src='/guayaquil.jpg' alt='UTFSM' />
        </Box>
        </Stack>

        </main>
      </div>
    )
  }