import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Box } from "@chakra-ui/react"
import { Button, ButtonGroup } from "@chakra-ui/react"
import { Input } from "@chakra-ui/react"
import { Text } from "@chakra-ui/react"
import { Stack } from "@chakra-ui/react"
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Registro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <Text fontSize="2xl">Registro</Text>
      <Box bg="#319795" w="40%" p={4} color="white">

        <Text fontSize="2xl">Correo Electrónico:</Text>
        <Input placeholder="user@gmail.com" />
        <Text fontSize="2xl">RUT:</Text>
        <Input placeholder="11.111.111-1" />
        <Text fontSize="2xl">Contraseña:</Text>
        <Input placeholder="" />
        <Text fontSize="2xl">Confirmar Contraseña:</Text>
        <Input placeholder="" />

      <Stack direction="row" spacing={4} align="center">
        <Button colorScheme="blue" size="md" onClick={() => router.push("postulacion")}>Regístrate</Button>
      </Stack>

        
        </Box>
      </main>
    </div>
  )
}